/**
 * Created by asus-pc on 2017/2/26.
 */
angular.module('serviceModel',[])
       .service('dataService1',function(){
        var menu=[
            {
                picture:"images/main-z-2.jpg",
                name:'满298减60，上不封顶',
                price1:1.4,
                price2:'折起',
                price3:'乔伊思女装专场',
                time:'剩3天',
                display:'block',
                opacity:0

            },
            {
                picture:"images/main-z-3.jpg",
                name:'.',
                price1:1.3,
                price2:'折起',
                price3:'缤慕promone女装专场',
                time:'剩16时',
                display:'none',
                opacity:0
            },
        {
            picture:"images/main-z-4.jpg",
            name:'满498减80，上不封顶',
            price1:0.9,
            price2:'折起',
            price3:'ZIMMUR女装专场',
            time:'剩5天',
            display:'block',
            opacity:0
        },
            {
                picture:"images/main-z-5.jpg",
                name:'满300减30，满500减60',
                price1:0.8,
                price2:'折起',
                price3:'Amii女装专场',
                time:'剩5天',
                display:'block',
                opacity:0

            },
            {
                picture:"images/main-z-6.jpg",
                name:'满300减30，满500减60',
                price1:0.8,
                price2:'折起',
                price3:'Amii女装专场',
                time:'剩5天',
                display:'block',
                opacity:0

            },
            {
                picture:"images/main-z-3.jpg",
                name:'.',
                price1:1.3,
                price2:'折起',
                price3:'缤慕promone女装专场',
                time:'剩16时',
                display:'none',
                opacity:0
            },
            {
                picture:"images/main-z-7.jpg",
                name:'满300减30，满500减60',
                price1:1.3,
                price2:'折起',
                price3:'缤慕promone女装专场',
                time:'剩16时',
                display:'block',
                opacity:0

            },
            {
                picture:"images/main-z-7.jpg",
                name:'满300减30，满500减60',
                price1:1.3,
                price2:'折起',
                price3:'缤慕promone女装专场',
                time:'剩16时',
                display:'block',
                opacity:0
            },
            {
                picture:"images/main-z-6.jpg",
                name:'满300减30，满500减60',
                price1:0.8,
                price2:'折起',
                price3:'Amii女装专场',
                time:'剩5天',
                display:'block',
                opacity:0

            },
            {
                picture:"images/main-z-4.jpg",
                name:'满498减80，上不封顶',
                price1:0.9,
                price2:'折起',
                price3:'ZIMMUR女装专场',
                time:'剩5天',
                display:'block',
                opacity:0
            }
        ];
        return menu;

    }).service('dataService2',function(){
    var menu2=[
        {
            picture:"images/main-shoe-1.jpg",
            price1:1.4,
            price2:'折起',
            price3:'乔伊思鞋包专场',
            time:'剩3天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-2.jpg",
            price1:1.3,
            price2:'折起',
            price3:'缤慕promone鞋包专场',
            time:'剩16时',
            display:'none',
            opacity:0
        },
        {
            picture:"images/main-shoe-3.jpg",
            price1:0.9,
            price2:'折起',
            price3:'ZIMMUR鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0
        },
        {
            picture:"images/main-shoe-4.jpg",
            price1:0.8,
            price2:'折起',
            price3:'Amii鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-5.jpg",
            price1:0.8,
            price2:'折起',
            price3:'Amii鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-6.jpg",
            price1:1.3,
            price2:'折起',
            price3:'缤慕promone鞋包专场',
            time:'剩16时',
            display:'none',
            opacity:0
        },
        {
            picture:"images/main-shoe-7.jpg",
            price1:1.3,
            price2:'折起',
            price3:'缤慕promone鞋包专场',
            time:'剩16时',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-8.jpg",
            price1:1.3,
            price2:'折起',
            price3:'缤慕promone鞋包专场',
            time:'剩16时',
            display:'block',
            opacity:0
        },
        {
            picture:"images/main-shoe-9.jpg",
            price1:0.8,
            price2:'折起',
            price3:'Amii鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-10.jpg",
            price1:0.9,
            price2:'折起',
            price3:'ZIMMUR鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0
        },
        {
            picture:"images/main-shoe-11.jpg",
            price1:1.4,
            price2:'折起',
            price3:'乔伊思鞋包专场',
            time:'剩3天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-12.jpg",
            price1:1.3,
            price2:'折起',
            price3:'缤慕promone鞋包专场',
            time:'剩16时',
            display:'none',
            opacity:0
        },
        {
            picture:"images/main-shoe-13.jpg",
            price1:0.9,
            price2:'折起',
            price3:'ZIMMUR鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0
        },
        {
            picture:"images/main-shoe-14.jpg",
            price1:0.8,
            price2:'折起',
            price3:'Amii鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-15.jpg",
            price1:0.8,
            price2:'折起',
            price3:'Amii鞋包专场',
            time:'剩5天',
            display:'block',
            opacity:0

        },
        {
            picture:"images/main-shoe-16.jpg",
            price1:1.3,
            price2:'折起',
            price3:'缤慕promone鞋包专场',
            time:'剩16时',
            display:'none',
            opacity:0
        }
    ];
    return menu2;

});